# Generated by Django 5.2.5 on 2025-08-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importado', models.BooleanField(default=False, verbose_name='Importado')),
                ('created', models.DateTimeField(max_length=8, verbose_name='NCM')),
                ('produto', models.CharField(max_length=100, unique=True, verbose_name='Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Estoque atual')),
                ('estoque_minimo', models.PositiveBigIntegerField(default=0, verbose_name='Estoque mínimo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ('produto',),
            },
        ),
    ]
